### ISSUE TITLE
(experimental feat. ) declarative mdx query composor

### ISSUE THREAD

**Issue by Cubewise-JoeCHK** [airflow-provider-tm1/airflow-provider-tm1#10]
create a new issue for the #6 

the output would be a string of mdx query 
```python

def MDXQueryDrafter( 
  cube_name: str, 
  payload: dict, 
  **kwargs,
):
   return """
   SELECT 
     {[DIM_1].[HIE_1].[ELE]} 
   * {TM1SUBSETALL([DIM_2],[HIE_2])}
   ON ROWS, 
     {[DIM_3].[DHIE_3].[ELE]}
   ON COLUMNS,
   FROM [CUBE_NAME]
   """

```

**Comment by Cubewise-JoeCHK** [comment]
the pytest test case is required

#todo: the unittest for the mdx composer 
- [x] .gitworkflow add a new task for unittest 
- [x] docstring to use this function

**Comment by Cubewise-JoeCHK** [comment]
on scheudle: 
- [ ] retrieve dimension properties
- [ ] apply where function
- [ ] simple range, union, excepts, leveling, wildcard operation
```
range: ('abc', 'def') => [abc]:[def]
union: [1, 2, 3] => {[1] + [2] + [3]}
except: [1, 2, 3] => union(except_list) => EXCEPTS({subset_mdx}, {[1], [2], [3]})
leveling: TM1FilterByLevel({subset_mdx}, level);
wild card: TM1FilterByPattern({subset_mdx}, pattern, attribute)
```
